export interface Database {
  public: {
    Tables: {
      yachts: {
        Row: {
          id: string;
          slug: string;
          name: string;
          tagline: string;
          description: string;
          builder: string;
          year: number;
          refit: number | null;
          length_ft: number;
          length_m: number;
          capacity: number;
          cabins: number | null;
          location: string;
          featured: boolean;
          youtube_shorts: string[];
          youtube_video: string;
          show_videos: boolean;
          daily_rules: string;
          weekly_rules: string;
          min_hours_weekday: number;
          min_hours_weekend: number;
          currency: string;
          calendar_id: string | null;
          booking_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          tagline?: string;
          description?: string;
          builder?: string;
          year?: number;
          refit?: number | null;
          length_ft?: number;
          length_m?: number;
          capacity?: number;
          cabins?: number | null;
          location?: string;
          featured?: boolean;
          youtube_shorts?: string[];
          youtube_video?: string;
          show_videos?: boolean;
          daily_rules?: string;
          weekly_rules?: string;
          min_hours_weekday?: number;
          min_hours_weekend?: number;
          currency?: string;
          calendar_id?: string | null;
          booking_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          tagline?: string;
          description?: string;
          builder?: string;
          year?: number;
          refit?: number | null;
          length_ft?: number;
          length_m?: number;
          capacity?: number;
          cabins?: number | null;
          location?: string;
          featured?: boolean;
          youtube_shorts?: string[];
          youtube_video?: string;
          show_videos?: boolean;
          daily_rules?: string;
          weekly_rules?: string;
          min_hours_weekday?: number;
          min_hours_weekend?: number;
          currency?: string;
          calendar_id?: string | null;
          booking_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      yacht_images: {
        Row: {
          id: string;
          yacht_id: string;
          url: string;
          storage_path: string;
          category: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          url: string;
          storage_path?: string;
          category?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          url?: string;
          storage_path?: string;
          category?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      yacht_specs: {
        Row: {
          id: string;
          yacht_id: string;
          label: string;
          value: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          label: string;
          value: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          label?: string;
          value?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      yacht_amenities: {
        Row: {
          id: string;
          yacht_id: string;
          icon: string;
          label: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          icon?: string;
          label: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          icon?: string;
          label?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      yacht_pricing: {
        Row: {
          id: string;
          yacht_id: string;
          season: string;
          period: string;
          hourly: number | null;
          daily: number | null;
          weekly: number | null;
          monthly: number | null;
          hourly_b2b: number | null;
          daily_b2b: number | null;
          weekly_b2b: number | null;
          monthly_b2b: number | null;
          sort_order: number;
          valid_from: string | null;
          valid_to: string | null;
          is_weekend: boolean;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          season: string;
          period: string;
          hourly?: number | null;
          daily?: number | null;
          weekly?: number | null;
          monthly?: number | null;
          hourly_b2b?: number | null;
          daily_b2b?: number | null;
          weekly_b2b?: number | null;
          monthly_b2b?: number | null;
          sort_order?: number;
          valid_from?: string | null;
          valid_to?: string | null;
          is_weekend?: boolean;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          season?: string;
          period?: string;
          hourly?: number | null;
          daily?: number | null;
          weekly?: number | null;
          monthly?: number | null;
          hourly_b2b?: number | null;
          daily_b2b?: number | null;
          weekly_b2b?: number | null;
          monthly_b2b?: number | null;
          sort_order?: number;
          valid_from?: string | null;
          valid_to?: string | null;
          is_weekend?: boolean;
        };
        Relationships: [];
      };
      yacht_included: {
        Row: {
          id: string;
          yacht_id: string;
          item: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          item: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          item?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      destinations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          short_description: string | null;
          sailing_time: string;
          best_for: string[];
          image: string;
          cover_image: string | null;
          gallery_images: string[];
          highlights: string[];
          sort_order: number;
          category: string;
          duration: string | null;
          price_from: number | null;
          latitude: number | null;
          longitude: number | null;
          map_label: string | null;
          video_url: string | null;
          featured: boolean;
          what_included: string[];
          itinerary: string[];
          map_x: number | null;
          map_y: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string;
          short_description?: string | null;
          sailing_time?: string;
          best_for?: string[];
          image?: string;
          cover_image?: string | null;
          gallery_images?: string[];
          highlights?: string[];
          sort_order?: number;
          category?: string;
          duration?: string | null;
          price_from?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          map_label?: string | null;
          video_url?: string | null;
          featured?: boolean;
          what_included?: string[];
          itinerary?: string[];
          map_x?: number | null;
          map_y?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          short_description?: string | null;
          sailing_time?: string;
          best_for?: string[];
          image?: string;
          cover_image?: string | null;
          gallery_images?: string[];
          highlights?: string[];
          sort_order?: number;
          category?: string;
          duration?: string | null;
          price_from?: number | null;
          latitude?: number | null;
          longitude?: number | null;
          map_label?: string | null;
          video_url?: string | null;
          featured?: boolean;
          what_included?: string[];
          itinerary?: string[];
          map_x?: number | null;
          map_y?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      analytics_reports: {
        Row: {
          id: string;
          period_start: string;
          period_end: string;
          raw_metrics: Record<string, unknown>;
          trends: Record<string, unknown> | null;
          summary: string | null;
          page_insights: Record<string, unknown>[] | null;
          traffic_analysis: Record<string, unknown> | null;
          quick_wins: Record<string, unknown>[] | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          period_start: string;
          period_end: string;
          raw_metrics: Record<string, unknown>;
          trends?: Record<string, unknown> | null;
          summary?: string | null;
          page_insights?: Record<string, unknown>[] | null;
          traffic_analysis?: Record<string, unknown> | null;
          quick_wins?: Record<string, unknown>[] | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          period_start?: string;
          period_end?: string;
          raw_metrics?: Record<string, unknown>;
          trends?: Record<string, unknown> | null;
          summary?: string | null;
          page_insights?: Record<string, unknown>[] | null;
          traffic_analysis?: Record<string, unknown> | null;
          quick_wins?: Record<string, unknown>[] | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      analytics_hypotheses: {
        Row: {
          id: string;
          report_id: string;
          title: string;
          problem: string;
          solution: string;
          expected_impact: string | null;
          priority: string;
          category: string;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          title: string;
          problem: string;
          solution: string;
          expected_impact?: string | null;
          priority: string;
          category: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          report_id?: string;
          title?: string;
          problem?: string;
          solution?: string;
          expected_impact?: string | null;
          priority?: string;
          category?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ads_reports: {
        Row: {
          id: string;
          period_start: string;
          period_end: string;
          account_metrics: Record<string, unknown>;
          trends: Record<string, unknown> | null;
          entities: Record<string, unknown>[] | null;
          summary: string | null;
          opportunity_score: number | null;
          anomalies: Record<string, unknown>[] | null;
          benchmarks: Record<string, unknown>[] | null;
          site_signals: Record<string, unknown> | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          period_start: string;
          period_end: string;
          account_metrics: Record<string, unknown>;
          trends?: Record<string, unknown> | null;
          entities?: Record<string, unknown>[] | null;
          summary?: string | null;
          opportunity_score?: number | null;
          anomalies?: Record<string, unknown>[] | null;
          benchmarks?: Record<string, unknown>[] | null;
          site_signals?: Record<string, unknown> | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          period_start?: string;
          period_end?: string;
          account_metrics?: Record<string, unknown>;
          trends?: Record<string, unknown> | null;
          entities?: Record<string, unknown>[] | null;
          summary?: string | null;
          opportunity_score?: number | null;
          anomalies?: Record<string, unknown>[] | null;
          benchmarks?: Record<string, unknown>[] | null;
          site_signals?: Record<string, unknown> | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ads_recommendations: {
        Row: {
          id: string;
          report_id: string;
          title: string;
          entity_level: string;
          entity_id: string | null;
          entity_name: string | null;
          problem: string;
          action: string;
          expected_impact: string | null;
          priority: string;
          action_type: string;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          report_id: string;
          title: string;
          entity_level?: string;
          entity_id?: string | null;
          entity_name?: string | null;
          problem: string;
          action: string;
          expected_impact?: string | null;
          priority?: string;
          action_type?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          report_id?: string;
          title?: string;
          entity_level?: string;
          entity_id?: string | null;
          entity_name?: string | null;
          problem?: string;
          action?: string;
          expected_impact?: string | null;
          priority?: string;
          action_type?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      extras: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          price: number;
          unit: string;
          category: string;
          image: string;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string;
          price: number;
          unit: string;
          category?: string;
          image?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          price?: number;
          unit?: string;
          category?: string;
          image?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          yacht_id: string;
          status: string;
          starts_at: string;
          ends_at: string;
          hours: number;
          guests: number;
          customer_name: string | null;
          customer_email: string | null;
          customer_phone: string | null;
          source: string;
          base_amount: number;
          extras_amount: number;
          bonus_hours: number;
          total_amount: number;
          deposit_amount: number;
          currency: string;
          quote_expires_at: string | null;
          hold_expires_at: string | null;
          stripe_checkout_id: string | null;
          stripe_payment_intent_id: string | null;
          gcal_event_id: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          yacht_id: string;
          status?: string;
          starts_at: string;
          ends_at: string;
          hours: number;
          guests: number;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          source?: string;
          base_amount?: number;
          extras_amount?: number;
          bonus_hours?: number;
          total_amount?: number;
          deposit_amount?: number;
          currency?: string;
          quote_expires_at?: string | null;
          hold_expires_at?: string | null;
          stripe_checkout_id?: string | null;
          stripe_payment_intent_id?: string | null;
          gcal_event_id?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          yacht_id?: string;
          status?: string;
          starts_at?: string;
          ends_at?: string;
          hours?: number;
          guests?: number;
          customer_name?: string | null;
          customer_email?: string | null;
          customer_phone?: string | null;
          source?: string;
          base_amount?: number;
          extras_amount?: number;
          bonus_hours?: number;
          total_amount?: number;
          deposit_amount?: number;
          currency?: string;
          quote_expires_at?: string | null;
          hold_expires_at?: string | null;
          stripe_checkout_id?: string | null;
          stripe_payment_intent_id?: string | null;
          gcal_event_id?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      booking_extras: {
        Row: {
          id: string;
          booking_id: string;
          extra_id: string;
          qty: number;
          unit_price: number;
          amount: number;
        };
        Insert: {
          id?: string;
          booking_id: string;
          extra_id: string;
          qty?: number;
          unit_price: number;
          amount: number;
        };
        Update: {
          id?: string;
          booking_id?: string;
          extra_id?: string;
          qty?: number;
          unit_price?: number;
          amount?: number;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          inquiry_type: string;
          preferred_date: string | null;
          message: string;
          source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string;
          inquiry_type?: string;
          preferred_date?: string | null;
          message?: string;
          source?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          inquiry_type?: string;
          preferred_date?: string | null;
          message?: string;
          source?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          processed_at: string;
        };
        Insert: {
          id: string;
          type: string;
          processed_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          processed_at?: string;
        };
        Relationships: [];
      };
      sale_listings: {
        Row: {
          id: string;
          slug: string;
          status: "draft" | "published" | "under_offer" | "sold";
          fleet_yacht_slug: string | null;
          name: string;
          builder: string | null;
          model: string | null;
          year_built: number | null;
          refit_year: number | null;
          length_m: number | null;
          beam_m: number | null;
          draft_m: number | null;
          guests: number | null;
          cabins: number | null;
          engines: string | null;
          top_speed_kn: number | null;
          lying: string | null;
          flag: string | null;
          price_amount: number | null;
          price_currency: string;
          headline: string | null;
          summary: string | null;
          description: string | null;
          highlights: string[];
          features: string[];
          spec_sections: unknown;
          faq: unknown;
          seo_title: string | null;
          seo_description: string | null;
          keywords: string[];
          hero_image: string | null;
          broker_terms: string | null;
          sort_order: number;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Omit<Database["public"]["Tables"]["sale_listings"]["Row"], "slug" | "name">> & {
          slug: string;
          name: string;
        };
        Update: Partial<Database["public"]["Tables"]["sale_listings"]["Row"]>;
        Relationships: [];
      };
      sale_media: {
        Row: {
          id: string;
          listing_id: string;
          kind: "image" | "video" | "youtube";
          url: string;
          storage_path: string | null;
          caption: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          kind: "image" | "video" | "youtube";
          url: string;
          storage_path?: string | null;
          caption?: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sale_media"]["Row"]>;
        Relationships: [];
      };
      sale_materials: {
        Row: {
          id: string;
          listing_id: string;
          title: string;
          description: string;
          category: "specification" | "brochure" | "photos" | "video" | "survey" | "document" | "other";
          source: "bundled" | "storage" | "url";
          location: string;
          file_name: string;
          mime_type: string;
          size_bytes: number | null;
          active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          title: string;
          description?: string;
          category?: "specification" | "brochure" | "photos" | "video" | "survey" | "document" | "other";
          source: "bundled" | "storage" | "url";
          location: string;
          file_name: string;
          mime_type?: string;
          size_bytes?: number | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sale_materials"]["Row"]>;
        Relationships: [];
      };
      sale_download_requests: {
        Row: {
          id: string;
          listing_id: string | null;
          listing_slug: string;
          email: string;
          is_broker: boolean;
          company: string | null;
          client_name: string | null;
          materials: unknown;
          ip: string | null;
          user_agent: string | null;
          referrer: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          listing_id?: string | null;
          listing_slug: string;
          email: string;
          is_broker?: boolean;
          company?: string | null;
          client_name?: string | null;
          materials?: unknown;
          ip?: string | null;
          user_agent?: string | null;
          referrer?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sale_download_requests"]["Row"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      image_category: "hero" | "exterior" | "interior" | "cabin" | "deck" | "dining" | "other";
    };
  };
}

export type Yacht = Database["public"]["Tables"]["yachts"]["Row"];
export type YachtImage = Database["public"]["Tables"]["yacht_images"]["Row"];
export type YachtSpec = Database["public"]["Tables"]["yacht_specs"]["Row"];
export type YachtAmenity = Database["public"]["Tables"]["yacht_amenities"]["Row"];
export type YachtPricing = Database["public"]["Tables"]["yacht_pricing"]["Row"];
export type YachtIncluded = Database["public"]["Tables"]["yacht_included"]["Row"];
export type DestinationRow = Database["public"]["Tables"]["destinations"]["Row"];
export type ExtraRow = Database["public"]["Tables"]["extras"]["Row"];
export type BookingRow = Database["public"]["Tables"]["bookings"]["Row"];
export type BookingExtraRow = Database["public"]["Tables"]["booking_extras"]["Row"];
export type LeadRow = Database["public"]["Tables"]["leads"]["Row"];
export type StripeEventRow = Database["public"]["Tables"]["stripe_events"]["Row"];
export type SaleListingRow = Database["public"]["Tables"]["sale_listings"]["Row"];
export type SaleMediaRow = Database["public"]["Tables"]["sale_media"]["Row"];
export type SaleMaterialRow = Database["public"]["Tables"]["sale_materials"]["Row"];
export type SaleDownloadRequestRow = Database["public"]["Tables"]["sale_download_requests"]["Row"];
